# Continuous integration test of any branch.

name: CI
on:
  push:
    branches-ignore:
    - main

jobs:
  # Run Python tests on Github runner
  run_tox_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Checkout github repo
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        $CONDA/bin/conda install -y -c bioconda womtool 
        $CONDA/bin/conda config --add channels conda-forge
        $CONDA/bin/conda install -y -c conda-forge miniwdl shellcheck
        echo "$CONDA/bin" >> $GITHUB_PATH

    - name: Test with tox
      run: tox

  # Build Docker image
  build_docker_images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout github repo
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Build Docker images
      run: |-
        gcloud config set account aou-lr-docker-builder@broad-dsp-lrma.iam.gserviceaccount.com
        gcloud auth configure-docker -q us-central1-docker.pkg.dev
        ./scripts/build_docker_images.sh $(git rev-parse --abbrev-ref HEAD)

